---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgBecQjFQUReAk1zPRhXBeUOOpWMKcJ22mMJaXiziy1r6g+yEtzVztTHC8yePZnt61MrOAtKQ+cUQHbMyE2SVAx6VkcyJefBM6sdqb12aldOMVjk5QXhYgZYXwHJ+oKrgATk+tLZOfnZ8Ox9u0b3s9XLYJqXnXpQNNKHBW0DMOxjxDlVddRgy00J868fD0cDYwef6Xqls+qAXSzPN7ohT6AjbsdR2QzNjhF0C7bF5PlgjCaeXQM0o7DDgkDh29reXLgnkTptjMwTpuUtacq1h1x0B1opMnxjVGT5PUAFJwuKcwtwfIieCAmr29+YdIrjDsNn1LgGTdh3FDx594Y2/qWLPJm4zUG9ofFZ43sKsJdP2ZCDorG7WORxCvk/V/jhJrAlLJ0sLBq45OuRKcI1VxQopAbN9xGNrk0RwEYPRvb4FRMMQ0KuBxiTWim42tkbS6ikFDMg6I3H/zk8HNiymiFviMeayJRMF38RPBfLEwwOFuZMdsF4m+3KA5mHcpzqKVJOPGCnmeqUV+qDx++U8OErWahMebOWV0ClEtCk4YMeFATdW/LGbjg3IrgOF5SMt1Q6E5s61uheyYO1HNVjojM5BIg9csu1KBl/qYA3l+SbhzEnPU28JqjhM6p2x63hYD4+Lz51aO7VzYcHdJTxTtqpKF3HcXGLptMRtlkvik/u2PlqnUcXpDzwA7cOSPmFKC15ONkUdQjOYt4M8ygo+pr5938=
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: dev
