---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgA+FW2uAk2Mv8n83ER32xV7EH4zqmc9/u50Az9taTe5E0xC0tQ8XmMHHRZVynApGFqtbT5J4YMmsQfScKIx+EAKciSI5S4rs8l14R5o6q5Ksz7CGN5oRDiTQegelkq9S4hej4zUsIPTkpn5y7IWokTGuTh5CC91nrUIIxUOhfHREPCJy+X32WnOi19sx3s2AUDk1eilZ3Pi8aHRc3cHjSft0SRZ2D6ni5SAbeb9xeLoU13yFJGMr9+sah3RRq+FoM7GGTSq20njFRu9UKxWd+/heiZend3bMhwkmHIvFqliSjKCoLsyglrPB1r/XRYJdk80RRJZSDmFV2aeGBibjGtKoBQwMdR8bHfJkoehV+aXMlLsX9p+3ruuGnrPtGcnq+PHVENkXrOZmGi9vqtw8nBqo0wN4GKo1GoeFJtTrGgKCPuB9vx6vNqjKNo/43Qsz0RfuQffMTKMGp6xE6HDUtqgqtm4B4XfF+aNMntQg+HusgVb6arqewMdVrKzwfJDMw2yeVAKpBZ9xgXDrmENMldE4Qv/0QUuRysqFgCU9Vci4bHAEU67eV31r+d3J5GET75sulgpni4hfSRrCff8UfhXLzrInCgyZ1z/vdfRxaplyytAwK8+CkDqgFa8rcgAKdULpPnPV0fnN+1vpZ4oMsZYU6DJrQewbXcz/7AbLzkjhnm9sYbWMWdPwbOrqUVFcZAXj/bXXKuTStP7WZ4Ap1qiqH4=
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: dev
