---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgCrHrK0k3NW9T1OPcMuzj1oJw2Dm6DQPjK1E6Jx6HHKNjoWAk2tMDosqg42qED/oPsSSaWj6HR+kba/H4xI54TlN3WVsMj5R7lKTPqSCnhs2YnU4kgAiZZd1wWo9KPZLMQ36TXXeU3OzV81IqH0k0+sFyg/k2N7PxaIBYi0gcxUG2Q/8OQFFxgbUx2DPNy65YMtqaMwiqYRmIZtohvluqeIBAJ3lvFDbAsj8Ko7LMK2L4N34hmwTvWiMAEibVaqt2goSxhBDfBRaLOJ/BMAXZnpfJE7zbNTnuj5KjTFvg0VMPwOqVSoyjgM0PywBDC2J3vSGtzPtdpERrWHDo8m9mfG0EF08byMMx0GBhDCiyraItk1Sm03hdqVTRckwCiw3pvPzwuIME1qWIuDcPll40JdopRp/nyFcxuniXXmEdBjFyllL425dI8MFW9KSSdoZpdoTf65GI4P0OhoBToxjZqpe1O3NuGJuMBApD5YBfGtMTbW1PDZw3J9fBkc7WBQJv/haL7lOYXQZwvqPLbO3dQrF+1I/X5/03zqOuXRYVFjCZk9cUI6DxmcrzymhFsBskHdvZSY3SCaueoX86zZek5HFPxFIrI7kpdPLZqHr04bWtpjB0xuYBhrXrC3/rEAxSO5RtF+dN6XQuBBUOdX4/AM6xc2feOkSt76z6uvf3GKOg0aTVK67VaprohQpZo57rbX4fC6kYYa497nNLXckMzCkk8=
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: dev
