---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgA3ChvpPAatur98KsgJeVKEYqsPrNbboqPC8xAQ4cXkuAs1HC1sZ/OD/g8Oc3VvLHz5HVMXZeR028MND/Vcy0VS7cKdEnFylJn1YzYwpbCfIqIpLXQMsKzpVaKNv1s0yWjkgORHhlM6Zc83MUhbZemAaH9wCTS5yaVAPiB6HXGE40LRGfeijrozVvDHjzgqpas06IOvsYZIud6pR3cD65LQ25dvoPOF2If9bKZSFEF9GKLs5wxox5n3aVwC+Js0KFMs1rSsU0bkA9xHUFMuekK+VzLfkxg4PzDbk2WqWiVvVxn/tlhHXXNjebfekkW2AO3IIhrMTSX4U30cJ2UGcYcSf3xu6M6cuOOBxk9Se/qwtmR7H2fZuyhNDyG4eCciJD7bxIAaC/NzUDX6KMbU85WHNpW3EO9bplp7829VMc6HdXa41c6JPdcCecYcX6xuIt+xl9wNMdMpUbUo3jPSybtZhfPmwRVZBjnPkW4U6QMS50D2uF8nky3cHAt/KbBlfAiHNVB1Q4gHskRgJ5w7X9BQqluIZZBmlsmtBmclEWBQdk6FHitc0O+3WC6PIafRttf5O0QG52NmYl/ABSx5CcZ59+PG46uLZBXjQ9zGa5ZXQ8b1y0wtlYqzLesGCNhl46CQUBiXGZGO9r4XVAqJ6CMiOzCfi/TviTXGIFMOKXprWB942LJx1w7t4bxF9BriThVwPsBMLR0BYkR610biNKvm1sQ=
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: dev
