apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: soprahr
spec:
  selector:
    app: sonarqube
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:10.2-community
        env:
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://postgres:5432/sonarqube
        - name: SONARQUBE_JDBC_USERNAME
          value: sonar
        - name: SONARQUBE_JDBC_PASSWORD
          value: sonar
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /opt/sonarqube/data
          name: sonarqube-data
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
